# Generated by Django 4.0.4 on 2022-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonModel',
            new_name='Person',
        ),
    ]
